### ISSUE TITLE
关于Observer

### ISSUE THREAD

**Issue by Dknightsure** [qieguo2016/Vueuv#1]
## 求教
Observer.prototype.defineReactive方法中的Object.defineProperty方法中
```
if (Array.isArray(val)) {
     self.observeArray(val, dep);  // 递归监视，数组的监视要分开
 } else {
     self.observe(val);   // 递归对象属性到基本类型为止
 }
```

这个几行代码和外面的重复
```
if (Array.isArray(newVal)) {
       self.observeArray(newVal, dep);  // 递归监视，数组的监视要分开
} else {
       self.observe(newVal);   // 递归对象属性到基本类型为止
}
```

这里为何要重复监视？不懂

**Comment by qieguo2016** [comment]
这里不是重复监视。内部的是在设置新值的时候监视新值，后面一个是递归监视。
比如：
```javascript
data = {
  id: 1000,
  arr: [
    {uid: 100, name: 'A'},
    {uid: 200, name: 'B'},
  ]
};
```
外层的代码很好理解，就是递归监视子元素。比如上面的我监视了arr本身，然后再判断他是否为数组，如果是数组，就用监视数组的方式，否则就用监视对象的方法。
arr虽然是个数组，但是数组本身就是一个对象，你是可以直接设置arr的：`data.arr=['new','new']`，所以先用Object.defineProperty来监视set，当你执行上面这个语句的时候，就可以触发set里面的notify方法。但是这个新的`['new','new']`也是需要被监视的，所以就有了内层的那段代码。

**Comment by Dknightsure** [comment]
赞！看来是我对set的理解没到位，谢谢耐心解答～
