### ISSUE TITLE
关于Observer

### ISSUE THREAD

**Issue by Dknightsure** [qieguo2016/Vueuv#2]
# 哥们，又来问问题了-_-

```
set         : function (newVal) {
    if (val === newVal) {
        return;
    }
    val = newVal;  // setter本身已经做了赋值，val作为一个闭包变量，保存最新值
    if (Array.isArray(newVal)) {
      self.observeArray(newVal, dep);  // 递归监视，数组的监视要分开
    } else {
      self.observe(newVal);   // 递归对象属性到基本类型为止
    }
    dep.notify();  // 触发通知
}
```

假如一开始`data = { num: 3}`，后面赋值`data.num = 2`，`2`是以传值的方式赋给`newVal`的，这个时候监视`newVal`，而`data.num = 2`指的是另外一个内存，虽然`data.num`的值也是`2`，我的意思就是这里存在两块内存，而现在监视的是newVal那块内存，data.num是怎么监视成功的？

**Comment by qieguo2016** [comment]
内存？ 有点意思！
额，其实js中对象都是引用关系，如果传进来的newVa是一个对象的，那么data.num与newVal都是引用关系，共享内存，所以监视newVal与监视data.num都是一样的。
给你一个例子看看：
```javascript
function change(obj) {
   console.log(obj);
   obj.id = 9999;
   return obj;
}
var a = {id:1000,name:'Mark'};
var b = change(a);
```
你去控制台输入验证一下吧。
因为js这种引用机制，所以使用对象的传递很容易被篡改，所以会有很多深复制的面试题~~
也是因为这种问题的存在，所以react那种函数式编程就会出现Immutable这种库，引用赋值有利也有弊吧。

**Comment by Dknightsure** [comment]
谢谢你的例子，不过我不是那个意思  
javascript的函数是值传递，`data.num = 2`执行的时候，`set`方法里newVal虽然是2，但是这里的data.num和newVal都是基础类型，不是指向同一个2吧？

**Comment by qieguo2016** [comment]
看来上一个issue的东西你还没看懂呀。
这里递归的是监视newVal不错，但是你看看observe函数里面的递归终止条件，不是对象就不会监视的！
如果newVal={id:1000,name:'Jack'}这种我才会递归监视newVal的id和name！你给我传一个2，我是不会递归监视这个2的！
**另外，data.num的监视是这个ObjectDefineProperty里面已经在做的事情，并不需要再来一次递归才监视，所以你说的什么2啊、newVal对data.num的监视根本没影响。如果newVal是对象，我会监视这个对象下面的属性而已**

**Comment by Dknightsure** [comment]
醍醐灌顶  
谢谢啦，刚才走进死胡同犯蠢了。。。

**Comment by qieguo2016** [comment]
有时候看这些递归是会绕进去的，理清了之后就行了

**Comment by Dknightsure** [comment]
哈哈，刚入门前端，感觉自己进步不大，原地打滚，有什么好的学习建议吗？

**Comment by qieguo2016** [comment]
多思考，多留意资讯、开阔眼界。
